name: CI

on:
  push:
    branches: v1.1
  pull_request:

jobs:
  pipeline:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.1', '7.2', '7.3']
        nchan-client-version: ['^1.0', '^2.0']
        exclude:
          - operating-system: ubuntu-latest
            php-version: '7.1'
            nchan-client-version: '^2.0'
          - operating-system: ubuntu-latest
            php-version: '7.2'
            nchan-client-version: '^2.0'
    name: ${{ matrix.php-version }} with nchan-client ${{ matrix.nchan-client-version }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}

      - name: Prepare
        run: |
          composer install
          composer require marein/php-nchan-client:${{ matrix.nchan-client-version }}

      - name: Testsuite
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs tests src --standard=PSR2
          vendor/bin/phpstan analyse -l max src
