name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  pipeline:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.4', '8.0']
        nchan-client-version: ['^2.0', '^3.0']
        guzzle-version: ['^7.0']
        guzzle-psr7-version: ['^1.6', '^2.0']
        exclude:
          - php-version: '8.0'
            nchan-client-version: '^2.0'
    name: >
      ${{ matrix.php-version }}
      with nchan-client ${{ matrix.nchan-client-version }}
      and guzzle ${{ matrix.guzzle-version }}
      and guzzle-psr7 ${{ matrix.guzzle-psr7-version }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Prepare
        run: |
          composer install
          composer require \
            marein/php-nchan-client:${{ matrix.nchan-client-version }} \
            guzzlehttp/guzzle:${{ matrix.guzzle-version }} \
            guzzlehttp/psr7:${{ matrix.guzzle-psr7-version }} \
            --update-with-all-dependencies

      - name: Testsuite
        run: |
          vendor/bin/phpunit
          vendor/bin/phpcs
          vendor/bin/phpstan analyse
